root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  entrypoint = "./tmp/main"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  kill_delay = "200ms"
  send_interrupt = true

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
