name: Build

on:
  push:
    branches:
      - main
    paths:
      - "stashix_web/**"
      - ".forgejo/workflows/build.yaml"
  pull_request:
    paths:
      - "stashix_web/**"
      - ".forgejo/workflows/build.yaml"

jobs:
  build:
    runs-on: act-ubuntu-24.04-amd64

    steps:
      - name: checkout code
        uses: https://code.forgejo.org/actions/checkout@v7

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        uses: docker/build-push-action@v7
        with:
          context: stashix_web
          push: false
          tags: stashix:latest
