name: Backend Tests

on:
  push:
    paths:
      - "backend/**"
      - ".forgejo/workflows/test-backend.yaml"
  pull_request:
    paths:
      - "backend/**"
      - ".forgejo/workflows/test-backend.yaml"

jobs:
  test:
    runs-on: act-latest-amd64

    steps:
      - name: checkout code
        uses: https://code.forgejo.org/actions/checkout@v7

      - name: setup go
        uses: https://code.forgejo.org/actions/setup-go@v7
        with:
          go-version-file: backend/go.mod

      - name: run tests
        run: go test ./...
        working-directory: backend
